# This configuration file is not a recommendation.
#
# We intentionally use a limited set of linters.
# This configuration file is used with different version of golangci-lint to avoid regressions:
# the linters can change between version,
# their configuration may be not compatible or their reports can be different,
# and this can break some of our tests.
# Also, some linters are not relevant for the project (e.g. linters related to SQL).
#
# We have specific constraints, so we use a specific configuration.
#
# See the file `.golangci.reference.yml` to have a list of all available configuration options.

version: "2"

linters:
  default: none
  # This list of linters is not a recommendation (same thing for all this configuration file).
  # We intentionally use a limited set of linters.
  # See the comment on top of this file.
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    # - cyclop # Already using gocyclo
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    # - errcheck # Pending implementation
    # - errchkjson # Pending implementation
    - errorlint
    - exhaustive
    # - exhaustruct # A lot of warnings on this rule
    - fatcontext
    - forbidigo
    - funlen
    # - gci # Check if formatted; a lot of warnings
    - ginkgolinter
    - gochecksumtype
    - gocognit
    # - goconst # Pending evaluation
    # - gocritic # Pending implementation - essential for code quality and performance
    - gocyclo
    - godot
    # - godox
    # - gofumpt # Already use gofmt
    - gomoddirectives
    - gomodguard
    - goheader
    - gosec
    - gosmopolitan
    - grouper
    # - govet # Pending evaluation
    - iface
    - importas
    # - inamedparam # Pending evaluation
    # - interfacebloat # Warning in Logger `the interface has more than 10 methods: 23`
    - ineffassign
    # - ireturn # Ignoring this for now
    # - lll # Ignoring this for now
    - loggercheck
    - maintidx
    - makezero
    - misspell
    # - mnd # Good but currently too much warning
    # - musttag # Pending implementation
    - nakedret
    - nestif
    # - nilnil # Pending evaluation
    # - nlreturn # Too nitpicky
    # - nolintlint # Pending evaluation
    # - paralleltest # Pending implementation
    # - perfsprint # Pending implementation
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    # - nonamedreturns # Prefer not to use this
    # - revive # Pending implementation
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    # - stylecheck # TODO
    # - tagalign # Pending implementation
    - tagliatelle
    # - testifylint # Pending evaluation
    # - testpackage
    - thelper
    - unconvert
    # - unparam # Pending evaluation
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen # Not preferred for now
    - whitespace
    # - wrapcheck
    # - wsl # Too nitpicky
    - containedctx

  settings:
    depguard:
      rules:
        logger:
          deny:
            # logging is allowed only by logutils.Log,
            - pkg: "github.com/sirupsen/logrus"
              desc: logging is allowed only by logutils.Log.
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package.
            - pkg: "github.com/instana/testify"
              desc: It's a fork of github.com/stretchr/testify.
          files:
            # logrus is allowed to use only in logutils package.
            - "!**/pkg/logutils/**.go"
    dupl:
      threshold: 100
    funlen:
      lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
      statements: 55
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
    gocyclo:
      min-complexity: 20
    godox:
      keywords:
        - FIXME
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
      enable:
        - nilness
        - shadow
    errorlint:
      asserts: false
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - "importas" # linter name
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
    tagliatelle:
      # Checks the struct tag name case.
      case:
        # Defines the association between tag name and case.
        # Any struct tag name can be used.
        # Supported string cases:
        # - `camel`
        # - `pascal`
        # - `kebab`
        # - `snake`
        # - `upperSnake`
        # - `goCamel`
        # - `goPascal`
        # - `goKebab`
        # - `goSnake`
        # - `upper`
        # - `lower`
        # - `header`
        rules:
          json: snake
          yaml: snake
          xml: goCamel
          toml: goCamel
          bson: goCamel
          avro: snake
          mapstructure: goCamel
          env: upperSnake
          envconfig: upperSnake
          whatever: snake
        # Defines the association between tag name and case.
        # Important: the `extended-rules` overrides `rules`.
        # Default: empty
        extended-rules:
          json:
            # Supported string cases:
            # - `camel`
            # - `pascal`
            # - `kebab`
            # - `snake`
            # - `upperSnake`
            # - `goCamel`
            # - `goPascal`
            # - `goKebab`
            # - `goSnake`
            # - `header`
            # - `lower`
            # - `header`
            #
            # Required
            case: snake
            # Adds 'AMQP', 'DB', 'GID', 'RTP', 'SIP', 'TS' to initialisms,
            # and removes 'LHS', 'RHS' from initialisms.
            # Default: false
            extra-initialisms: true
            # Defines initialism additions and overrides.
            # Default: empty
            initialism-overrides:
              DB: true # add a new initialism
              LHS: false # disable a default initialism.
              # ...
        # Uses the struct field name to check the name of the struct tag.
        # Default: false
        use-field-name: true
        # The field names to ignore.
        # Default: []
        ignored-fields:
          - ErrStatus
          - ErrError
          - ErrMessage
          - RandErrFactor
          - ContactIDs
        # Overrides the default/root configuration.
        # Default: []
        overrides:
          - # The package path (uses `/` only as a separator).
            # Required
            pkg: foo/bar
            # Default: empty or the same as the default/root configuration.
            rules:
              json: snake
              xml: pascal

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - test/testdata_etc # test files
      - internal/go # extracted from Go code
      - internal/x # extracted from x/tools code
      - pkg/goformatters/gci/internal # extracted from gci code
      - pkg/goanalysis/runner_checker.go # extracted from x/tools code
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - mnd
          - lll

      # Based on existing code, the modifications should be limited to make maintenance easier.
      - path: pkg/golinters/unused/unused.go
        linters: [gocritic]
        text: "rangeValCopy: each iteration copies 160 bytes \\(consider pointers or indexing\\)"

      # Related to migration command.
      - path: pkg/commands/internal/migrate/two/
        linters:
          - lll

      # Related to migration command.
      - path: pkg/commands/internal/migrate/
        linters:
          - gocritic
        text: "hugeParam:"

      # The codes are close but this is not duplication.
      - path: pkg/commands/(formatters|linters).go
        linters:
          - dupl

      # Deprecated linters
      - path: pkg/lint/lintersdb/builder_linter.go
        text: "SA1019: wsl.NewV4 is deprecated: use NewV5 instead."
        linters:
          - staticcheck
      - path: pkg/golinters/wsl/wsl.go
        text: "SA1019: config.WSLv4Settings is deprecated: use WSLv5Settings instead."
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint/v2
  exclusions:
    paths:
      - test/testdata_etc # test files
      - internal/go # extracted from Go code
      - internal/x # extracted from x/tools code
      - pkg/goformatters/gci/internal # extracted from gci code
      - pkg/goanalysis/runner_checker.go # extracted from x/tools code
