-- +goose Up
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','review_text','[{"type":"css","value":".shopee-product-rating__main-text"},{"type":"xpath","value":"//div[contains(@class,''product-rating__main'')]//p"},{"type":"css","value":"[data-sqe=''review-item-content'']"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','rating','[{"type":"css","value":".shopee-product-rating__rating-star--active"},{"type":"xpath","value":"//div[@class=''shopee-star-group'']/@data-score"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','author_name','[{"type":"css","value":".shopee-product-rating__author-name"},{"type":"xpath","value":"//div[contains(@class,''author-name'')]"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','author_id','[{"type":"jsonpath","value":"$.data.ratings[*].author_username"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','reviewed_at','[{"type":"css","value":".shopee-product-rating__time"},{"type":"jsonpath","value":"$.data.ratings[*].ctime"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','product_id','[{"type":"jsonpath","value":"$.data.item_id"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('shopee','xhr_pattern','[{"type":"regex","value":"shopee\\.co\\.id/api/v[0-9]+/item/get_ratings"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','review_text','[{"type":"css","value":"[data-testid=''review-description''] p"},{"type":"xpath","value":"//p[@itemprop=''description'']"},{"type":"css","value":".css-901oao"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','rating','[{"type":"css","value":"[data-testid=''icnStarRating'']"},{"type":"jsonpath","value":"$.data.productRevGetProductReviewList.data[*].rating"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','author_name','[{"type":"css","value":"[data-testid=''review-user-name'']"},{"type":"jsonpath","value":"$.data.productRevGetProductReviewList.data[*].reviewer.fullName"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','author_id','[{"type":"jsonpath","value":"$.data.productRevGetProductReviewList.data[*].reviewer.userID"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','reviewed_at','[{"type":"css","value":"[data-testid=''review-create-date'']"},{"type":"jsonpath","value":"$.data.productRevGetProductReviewList.data[*].createTime"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','product_id','[{"type":"jsonpath","value":"$.data.productRevGetProductReviewList.data[*].productID"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('tokopedia','xhr_pattern','[{"type":"regex","value":"tokopedia\\.com/graphql.*ProductRevGetProductReviewList"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','review_text','[{"type":"css","value":".pdp-review__desc"},{"type":"xpath","value":"//div[@class=''review-content'']//p"},{"type":"jsonpath","value":"$.data[*].review"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','rating','[{"type":"css","value":".pdp-review__rating-star--active"},{"type":"jsonpath","value":"$.data[*].rating"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','author_name','[{"type":"css","value":".pdp-review__user"},{"type":"jsonpath","value":"$.data[*].name"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','author_id','[{"type":"jsonpath","value":"$.data[*].customerId"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','reviewed_at','[{"type":"css","value":".pdp-review__date"},{"type":"jsonpath","value":"$.data[*].reviewDate"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','product_id','[{"type":"jsonpath","value":"$.data[*].productSku"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();
INSERT INTO selector_configs (platform, field, rules) VALUES ('blibli','xhr_pattern','[{"type":"regex","value":"blibli\\.com/api/reviews/products/"}]') ON CONFLICT (platform, field) DO UPDATE SET rules = EXCLUDED.rules, updated_at = NOW();

-- +goose Down
DELETE FROM selector_configs;
